# Generated by Django 5.2.5 on 2025-09-13 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_app', '0002_alter_compra_producto_alter_detalleventa_producto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='prod_precio_compra_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='prod_precio_venta_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='prod_stock_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='prod_venta_gte_compra',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='bodega_app.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega_app.producto'),
        ),
    ]
